name: Run pytests

on: [push]

jobs:

  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install application
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Install pytest and flake8
      run: |
        pip install pytest

    - name: Check syntax with flake8
      run: |
        flake8 --statistics --count --show-source --exclude=build --max-line-length=127

    - name: Test with pytest
      run: |
        pytest

    